### ISSUE TITLE
Consider converting this into a Terraform module

### ISSUE THREAD

**Issue by mrsimonemms** [MrSimonEmms/gitpod-k3s-guide#19]
Whilst talking with my friend @nandajavarma, we discussed ways of doing a v2 of this and converting this into a Terraform module which could then be published.

## Requirements:

1. it must be cloud-agnostic. Any compatible machine on any cloud should be able to run this
2. it must be Terraformable

## Suggestions:

 - Change this to using the official [k3s Ansible script](https://github.com/k3s-io/k3s-ansible) that can then be [plugged into Terraform](https://www.digitalocean.com/community/tutorials/how-to-use-ansible-with-terraform-for-configuration-management)

**Comment by Derroylo** [comment]
That sound like a great idea. I am using Terraform and Ansible to setup my whole cluster with Monitoring, Certmanager, Longhorn, MetalLB etc. but the most important part is missing, automatic installation of gitpod. Since you helped me so much in the past, dm me on discord if you want to have my current scripts or if i can help in any form.
